### ISSUE TITLE
App breaks at step 4 (Meet Uma)

### ISSUE THREAD

**Issue by scarabeo7** [CodeYourFuture/fieldtrip-js2-coworkers#4] opened 2022-09-21 08:51 UTC
The app breaks at step 4 (meet uma). Nothing happens when you click on the start button.

**Comment by djgrant** [comment] 2022-09-22 08:35
Hey @scarabeo7, thanks for reporting the issue. I can see that you reached the meet "meet malachi" stage. 

Can you help me to understand if the issue is within the web app or something on the back-end? Please open developer tools and open the console, then click the start button. Does any error message appear in the console?

**Comment by scarabeo7** [comment] 2022-09-22 09:26
![Screenshot 2022-09-22 at 10 25 25](https://user-images.githubusercontent.com/53916760/191710691-f066c6d9-3579-4b2f-a07e-82a157270274.png)

**Comment by djgrant** [comment] 2022-09-22 12:08
This looks like it might be coming from a Chrome extension – possibly the Loom extension (https://stackoverflow.com/a/73127878/5894687). Can you try disabling the extension if you have it?

**Comment by scarabeo7** [comment] 2022-09-22 12:20
Yep, that seem to have solved the TypeError, however, when you click still click on the blue start button nothing happens. 
![Screenshot 2022-09-22 at 13 16 36](https://user-images.githubusercontent.com/53916760/191744969-fa8e0d5a-ed51-4233-ac98-461799136f29.png)

**Comment by djgrant** [comment] 2022-10-17 12:14
hey @scarabeo7, sorry for the late reply to this. I had a bit of a deeper look this morning and it looks like something went wrong while creating a project board in your repo. I'm not sure exactly why this is. It would probably be best to click the 'Delete repository' button in the page you've screenshoted above and re-enroll in the course.

**Comment by scarabeo7** [comment] 2022-10-17 12:22
Yep no worries. 

I had to raise the issue as many trainees were facing the same problem
https://codeyourfuture.slack.com/archives/C012UUW69S8/p1663668911204149

**Comment by djgrant** [comment] 2022-10-25 12:52
It's something that's on my radar to be tackled after some more foundational work is addressed. Closing for now.

**Closed as completed by djgrant** 2022-10-25 12:52 UTC
